name: citytales
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  animate_do: ^4.2.0
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  # إضافة مكتبة الـ Bloc ضرورية عشان الـ Category Logic يشتغل
  flutter_bloc: ^8.1.6 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # تم تحديثها لنسخة تتوافق مع SDK 3.0

flutter:
  uses-material-design: true

  # التأكد من تعريف فولدر الصور
  assets:
    - assets/images/

  # تعريف الخطوط اللي ضفتيها
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Lobster Two
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf

    - family: PlaywriteIE
      fonts:
        - asset: assets/fonts/PlaywriteIE-VariableFont_wght.ttf

# إعدادات الـ Asset Generator (اختياري لو بتستخدمي الإضافة)
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants/
  filename: app_images.dart
  classname: AppImages
  ignore_comments: true